export enum AdminActivityType {
  LOGIN_REQUEST      = 'LOGIN_REQUEST',
  LOGIN_SUCCESS      = 'LOGIN_SUCCESS',
  LOGIN_FAILED       = 'LOGIN_FAILED',
  INVITE_ADMIN       = 'INVITE_ADMIN',
  ACCEPT_INVITE      = 'ACCEPT_INVITE',
  ACTIVATE           = 'ACTIVATE',
  DEACTIVATE         = 'DEACTIVATE',
  SUSPEND            = 'SUSPEND',
  UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS',
}
